language: generic

os: osx
osx_image: xcode10

rvm:
- 2.1.2

branches:
  only:
  - beta

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
  - unity_download_cache

before_install:
  - chmod -R a+rw ./unity_download_cache
  - openssl enc -aes-256-cbc -a -d -in setup_ssh.sh.enc -out ./Scripts/setup_ssh.sh -k ${ENCRYPTION_KEY}
  - chmod +x ./Scripts/setup_ssh.sh
  - . ./Scripts/setup_ssh.sh
  - bundle install

install:
  - . ./Scripts/install.sh

script:
  - . ./Scripts/build.sh

env:
  global:
  - UNITY_NOPROXY="localhost,127.0.0.1"
  - UNITY_DOWNLOAD_CACHE="${TRAVIS_BUILD_DIR}/unity_download_cache"
  - UNITY_PROJECT_NAME="UnityProject"
  - BUILD_PATH="${TRAVIS_BUILD_DIR}/Builds"
  - DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV"
